[package]
name = "sgx_tunittest"
version = "0.9.5"
authors = ["Baidu"]

[lib]
name = "sgx_tunittest"
path = "../../sgx_tunittest/src/lib.rs"
crate-type = ["rlib"]

[features]
default = []

[dependencies]